apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podinfo-dev

commonLabels:
  environment: dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - target:
      kind: Deployment
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: podinfo-dev.localtest.me
