apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-web-prod

commonLabels:
  environment: prod

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: sample-web
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: sample-web-content
  - target:
      kind: Ingress
      name: sample-web
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: sample-web-prod.localtest.me
